import type { Metadata } from "next";
import { inter, poppins, robotoMono } from "./ui/fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "CodeHug",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
         className={`${inter.variable} ${poppins.variable} ${robotoMono.variable} antialiased`}
      >
          {children}
      </body>
    </html>
  );
}
